### ISSUE TITLE
py2 vs py3 division

### ISSUE THREAD

**Issue by Kamuish** [Kamuish/serval#10]
Integer division in py2 -> integer as output 
in py3 -> float 

There are many functions depending on integer division -> possibly have to check them all

**Comment by j-faria** [comment]
try running in py2 with `-3` flag

**Comment by Kamuish** [comment]
When using the -brvref DRS we get the following problems 

- [x] sunrise.py -> not a problem, since he was already using the floor of the number.

- [x]  <>/SERVALHOME/py2_serval/serval/src/wstat.py:281: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.

  res = y - (wmean[s] if s else wmean)       # centering data
